// Generated by `libs/table/tools/generate-overloads.ts` — do not edit.
// Run `npm run table:overloads` to regenerate;
// `npm run table:overloads:check` fails if this file has drifted.

import type { Feature } from '../engine/types';
import type {
  ColumnDecl,
  ColumnValues,
  TableConfig,
  TableDataInput,
  TableStore,
} from './types';

/**
 * Call signatures for `createTable()` — one per feature-slot count, 0 to 15.
 * Slot k is typed against the store slots 1..k-1 have already built, so a feature sees
 * its predecessors and the return type is the full intersection.
 */
export interface CreateTableOverloads {
  <TRow, TCols extends readonly ColumnDecl<TRow, string, unknown>[]>(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
  ): TableStore<TRow, ColumnValues<TRow, TCols>>;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> & O1;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
    f5: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4,
      O5
    >,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
    f5: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4,
      O5
    >,
    f6: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5,
      O6
    >,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5 & O6;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
    f5: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4,
      O5
    >,
    f6: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5,
      O6
    >,
    f7: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5 & O6,
      O7
    >,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
    f5: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4,
      O5
    >,
    f6: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5,
      O6
    >,
    f7: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5 & O6,
      O7
    >,
    f8: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7,
      O8
    >,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
    f5: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4,
      O5
    >,
    f6: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5,
      O6
    >,
    f7: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5 & O6,
      O7
    >,
    f8: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7,
      O8
    >,
    f9: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8,
      O9
    >,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8 &
    O9;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
    f5: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4,
      O5
    >,
    f6: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5,
      O6
    >,
    f7: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5 & O6,
      O7
    >,
    f8: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7,
      O8
    >,
    f9: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8,
      O9
    >,
    f10: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9,
      O10
    >,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8 &
    O9 &
    O10;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
    f5: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4,
      O5
    >,
    f6: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5,
      O6
    >,
    f7: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5 & O6,
      O7
    >,
    f8: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7,
      O8
    >,
    f9: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8,
      O9
    >,
    f10: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9,
      O10
    >,
    f11: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10,
      O11
    >,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8 &
    O9 &
    O10 &
    O11;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
    f5: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4,
      O5
    >,
    f6: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5,
      O6
    >,
    f7: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5 & O6,
      O7
    >,
    f8: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7,
      O8
    >,
    f9: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8,
      O9
    >,
    f10: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9,
      O10
    >,
    f11: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10,
      O11
    >,
    f12: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11,
      O12
    >,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8 &
    O9 &
    O10 &
    O11 &
    O12;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
    O13 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
    f5: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4,
      O5
    >,
    f6: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5,
      O6
    >,
    f7: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5 & O6,
      O7
    >,
    f8: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7,
      O8
    >,
    f9: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8,
      O9
    >,
    f10: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9,
      O10
    >,
    f11: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10,
      O11
    >,
    f12: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11,
      O12
    >,
    f13: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12,
      O13
    >,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8 &
    O9 &
    O10 &
    O11 &
    O12 &
    O13;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
    O13 extends object,
    O14 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
    f5: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4,
      O5
    >,
    f6: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5,
      O6
    >,
    f7: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5 & O6,
      O7
    >,
    f8: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7,
      O8
    >,
    f9: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8,
      O9
    >,
    f10: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9,
      O10
    >,
    f11: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10,
      O11
    >,
    f12: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11,
      O12
    >,
    f13: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12,
      O13
    >,
    f14: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12 &
        O13,
      O14
    >,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8 &
    O9 &
    O10 &
    O11 &
    O12 &
    O13 &
    O14;
  <
    TRow,
    TCols extends readonly ColumnDecl<TRow, string, unknown>[],
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
    O13 extends object,
    O14 extends object,
    O15 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TCols>,
    f1: Feature<TableStore<TRow, ColumnValues<TRow, TCols>>, O1>,
    f2: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1, O2>,
    f3: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3, O4>,
    f5: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4,
      O5
    >,
    f6: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5,
      O6
    >,
    f7: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> & O1 & O2 & O3 & O4 & O5 & O6,
      O7
    >,
    f8: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7,
      O8
    >,
    f9: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8,
      O9
    >,
    f10: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9,
      O10
    >,
    f11: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10,
      O11
    >,
    f12: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11,
      O12
    >,
    f13: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12,
      O13
    >,
    f14: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12 &
        O13,
      O14
    >,
    f15: Feature<
      TableStore<TRow, ColumnValues<TRow, TCols>> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12 &
        O13 &
        O14,
      O15
    >,
  ): TableStore<TRow, ColumnValues<TRow, TCols>> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8 &
    O9 &
    O10 &
    O11 &
    O12 &
    O13 &
    O14 &
    O15;
}
