// Generated by `libs/table/tools/generate-overloads.ts` — do not edit.
// Run `npm run table:overloads` to regenerate;
// `npm run table:overloads:check` fails if this file has drifted.

import type { Feature } from '../engine/types';
import type { TableConfig, TableDataInput, TableStore } from './types';

/**
 * Call signatures for `createTable()` — one per feature-slot count, 0 to 15.
 * Slot k is typed against the store slots 1..k-1 have already built, so a feature sees
 * its predecessors and the return type is the full intersection.
 */
export interface CreateTableOverloads {
  <TRow, TId extends string>(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
  ): TableStore<TRow>;
  <TRow, TId extends string, O1 extends object>(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
  ): TableStore<TRow> & O1;
  <TRow, TId extends string, O1 extends object, O2 extends object>(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
  ): TableStore<TRow> & O1 & O2;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
  ): TableStore<TRow> & O1 & O2 & O3;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
  ): TableStore<TRow> & O1 & O2 & O3 & O4;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
    f5: Feature<TableStore<TRow> & O1 & O2 & O3 & O4, O5>,
  ): TableStore<TRow> & O1 & O2 & O3 & O4 & O5;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
    f5: Feature<TableStore<TRow> & O1 & O2 & O3 & O4, O5>,
    f6: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5, O6>,
  ): TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
    f5: Feature<TableStore<TRow> & O1 & O2 & O3 & O4, O5>,
    f6: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6, O7>,
  ): TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
    f5: Feature<TableStore<TRow> & O1 & O2 & O3 & O4, O5>,
    f6: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
  ): TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
    f5: Feature<TableStore<TRow> & O1 & O2 & O3 & O4, O5>,
    f6: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
  ): TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
    f5: Feature<TableStore<TRow> & O1 & O2 & O3 & O4, O5>,
    f6: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9,
      O10
    >,
  ): TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
    f5: Feature<TableStore<TRow> & O1 & O2 & O3 & O4, O5>,
    f6: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9,
      O10
    >,
    f11: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10,
      O11
    >,
  ): TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
    f5: Feature<TableStore<TRow> & O1 & O2 & O3 & O4, O5>,
    f6: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9,
      O10
    >,
    f11: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10,
      O11
    >,
    f12: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11,
      O12
    >,
  ): TableStore<TRow> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8 &
    O9 &
    O10 &
    O11 &
    O12;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
    O13 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
    f5: Feature<TableStore<TRow> & O1 & O2 & O3 & O4, O5>,
    f6: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9,
      O10
    >,
    f11: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10,
      O11
    >,
    f12: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11,
      O12
    >,
    f13: Feature<
      TableStore<TRow> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12,
      O13
    >,
  ): TableStore<TRow> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8 &
    O9 &
    O10 &
    O11 &
    O12 &
    O13;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
    O13 extends object,
    O14 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
    f5: Feature<TableStore<TRow> & O1 & O2 & O3 & O4, O5>,
    f6: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9,
      O10
    >,
    f11: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10,
      O11
    >,
    f12: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11,
      O12
    >,
    f13: Feature<
      TableStore<TRow> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12,
      O13
    >,
    f14: Feature<
      TableStore<TRow> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12 &
        O13,
      O14
    >,
  ): TableStore<TRow> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8 &
    O9 &
    O10 &
    O11 &
    O12 &
    O13 &
    O14;
  <
    TRow,
    TId extends string,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
    O13 extends object,
    O14 extends object,
    O15 extends object,
  >(
    data: TableDataInput<TRow>,
    config: TableConfig<TRow, TId>,
    f1: Feature<TableStore<TRow>, O1>,
    f2: Feature<TableStore<TRow> & O1, O2>,
    f3: Feature<TableStore<TRow> & O1 & O2, O3>,
    f4: Feature<TableStore<TRow> & O1 & O2 & O3, O4>,
    f5: Feature<TableStore<TRow> & O1 & O2 & O3 & O4, O5>,
    f6: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9,
      O10
    >,
    f11: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10,
      O11
    >,
    f12: Feature<
      TableStore<TRow> & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11,
      O12
    >,
    f13: Feature<
      TableStore<TRow> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12,
      O13
    >,
    f14: Feature<
      TableStore<TRow> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12 &
        O13,
      O14
    >,
    f15: Feature<
      TableStore<TRow> &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12 &
        O13 &
        O14,
      O15
    >,
  ): TableStore<TRow> &
    O1 &
    O2 &
    O3 &
    O4 &
    O5 &
    O6 &
    O7 &
    O8 &
    O9 &
    O10 &
    O11 &
    O12 &
    O13 &
    O14 &
    O15;
}
