/**
 * Generates the per-arity overload interfaces `createTable()` and `composeFeatures()` are
 * typed by — `src/api/create-table.overloads.ts` and
 * `src/api/features/compose-features.overloads.ts`.
 *
 * Run: `npm run table:overloads` (`-- --dry-run` prints, `-- --check` fails on drift).
 * Arity and the accumulation rule come from D27: slot k is typed against the
 * base ∩ every preceding slot's contribution, so argument order governs member visibility.
 *
 * Output is run through Prettier with the repo's own config, so `prettier --write` over the
 * emitted files is a no-op and the drift check never fights the formatter.
 */

import { readFileSync, writeFileSync } from 'node:fs';
import { join, posix, relative, resolve } from 'node:path';
import { format, resolveConfig } from 'prettier';

const LIB_ROOT = resolve(import.meta.dirname, '..');
const REPO_ROOT = resolve(LIB_ROOT, '..', '..');
const GENERATOR_PATH = 'libs/table/tools/generate-overloads.ts';

/** D27: 15 feature slots. A 16th argument matches no overload — that is the intended error. */
const ARITY = 15;

interface OverloadSpec {
  /** Name of the emitted call-signature interface. */
  name: string;
  /** JSDoc lines emitted above the interface, without the `*` prefixes. */
  doc: string[];
  /** Absolute path of the file it is emitted to. */
  outputFile: string;
  /** Import lines the emitted file needs. */
  imports: string[];
  /** Generic parameters carrying the accumulation base, e.g. `['TRow', 'TId extends string']`
   * or `['In extends Shape']`. */
  baseGenerics: string[];
  /** The type every slot's `In` and the return type accumulate onto. */
  base: string;
  /** Parameters emitted before the feature slots. */
  leadingParams: string[];
  /** Whether a zero-feature signature is emitted. */
  includeZeroFeature: boolean;
  /** Builds the return type from the base and the contributions of `featureCount` slots. */
  renderReturn: (base: string, featureCount: number) => string;
}

const CREATE_TABLE: OverloadSpec = {
  name: 'CreateTableOverloads',
  doc: [
    'Call signatures for `createTable()` — one per feature-slot count, 0 to 15.',
    'Slot k is typed against the store slots 1..k-1 have already built, so a feature sees',
    'its predecessors and the return type is the full intersection.',
  ],
  outputFile: join(LIB_ROOT, 'src', 'api', 'create-table.overloads.ts'),
  imports: [
    "import type { Feature } from '../engine/types';",
    "import type { TableConfig, TableDataInput, TableStore } from './types';",
  ],
  // `TId` flows from `config.columns` into every slot's `In` and into the return type
  // (ADR-0019's amendment).
  baseGenerics: ['TRow', 'TId extends string'],
  base: 'TableStore<TRow, TId>',
  leadingParams: ['data: TableDataInput<TRow>', 'config: TableConfig<TRow, TId>'],
  includeZeroFeature: true,
  renderReturn: (base, featureCount) =>
    [base, ...contributions(featureCount)].join(' & '),
};

const COMPOSE_FEATURES: OverloadSpec = {
  name: 'ComposeFeaturesOverloads',
  doc: [
    'Call signatures for `composeFeatures()` — the same left-to-right accumulation as',
    '`createTable()`, collapsed into one `Feature<In, …>` so a bundle costs a single slot.',
  ],
  outputFile: join(
    LIB_ROOT,
    'src',
    'api',
    'features',
    'compose-features.overloads.ts'
  ),
  imports: ["import type { Feature, Shape } from '../../engine/types';"],
  baseGenerics: ['In extends Shape'],
  base: 'In',
  leadingParams: [],
  includeZeroFeature: false,
  renderReturn: (base, featureCount) =>
    `Feature<${base}, ${contributions(featureCount).join(' & ')}>`,
};

const SPECS = [CREATE_TABLE, COMPOSE_FEATURES];

function toHref(absolutePath: string): string {
  return relative(REPO_ROOT, absolutePath).split('\\').join(posix.sep);
}

/** `['O1', ..., 'On']` — one contribution type parameter per feature slot. */
function contributions(count: number): string[] {
  return Array.from({ length: count }, (_, index) => `O${index + 1}`);
}

/** The `In` of slot k: the base intersected with every preceding slot's contribution. */
function renderSlotInput(base: string, slot: number): string {
  return [base, ...contributions(slot - 1)].join(' & ');
}

function renderSignature(spec: OverloadSpec, featureCount: number): string {
  const generics = [
    ...spec.baseGenerics,
    ...contributions(featureCount).map(
      (contribution) => `${contribution} extends object`
    ),
  ].join(', ');

  const featureParams = contributions(featureCount).map(
    (contribution, index) =>
      `f${index + 1}: Feature<${renderSlotInput(spec.base, index + 1)}, ${contribution}>`
  );

  const params = [...spec.leadingParams, ...featureParams].join(', ');

  return `<${generics}>(${params}): ${spec.renderReturn(spec.base, featureCount)};`;
}

function renderHeader(spec: OverloadSpec): string {
  return [
    `// Generated by \`${GENERATOR_PATH}\` — do not edit.`,
    '// Run `npm run table:overloads` to regenerate;',
    '// `npm run table:overloads:check` fails if this file has drifted.',
    '',
    ...spec.imports,
    '',
  ].join('\n');
}

function renderOverloads(spec: OverloadSpec): string {
  const firstCount = spec.includeZeroFeature ? 0 : 1;
  const signatures = Array.from(
    { length: ARITY - firstCount + 1 },
    (_, index) => renderSignature(spec, firstCount + index)
  );

  return [
    renderHeader(spec),
    '/**',
    ...spec.doc.map((line) => ` * ${line}`),
    ' */',
    `export interface ${spec.name} {`,
    ...signatures,
    '}',
    '',
  ].join('\n');
}

/** Emitted source, formatted with the repo's Prettier config for the output file's path. */
async function renderFormatted(spec: OverloadSpec): Promise<string> {
  const options = await resolveConfig(spec.outputFile);
  return format(renderOverloads(spec), {
    ...options,
    filepath: spec.outputFile,
    parser: 'typescript',
  });
}

function readIfPresent(file: string): string | null {
  try {
    return readFileSync(file, 'utf8');
  } catch {
    return null;
  }
}

async function main(): Promise<void> {
  // `--check` wins: printing and comparing are mutually exclusive, and silently reporting
  // "up to date" after skipping every comparison is the worse failure.
  const isCheck = process.argv.includes('--check');
  const isDryRun = !isCheck && process.argv.includes('--dry-run');
  const drifted: string[] = [];

  for (const spec of SPECS) {
    const output = await renderFormatted(spec);
    const href = toHref(spec.outputFile);

    if (isDryRun) {
      process.stdout.write(output);
      continue;
    }

    if (isCheck) {
      if (readIfPresent(spec.outputFile) !== output) {
        drifted.push(href);
      }
      continue;
    }

    writeFileSync(spec.outputFile, output, 'utf8');
    process.stdout.write(`Wrote ${href} — ${spec.name}.\n`);
  }

  if (!isCheck) {
    return;
  }

  if (drifted.length > 0) {
    process.stderr.write(
      'Generated overloads are stale — run `npm run table:overloads`:\n'
    );
    for (const href of drifted) {
      process.stderr.write(`  ${href}\n`);
    }
    process.exitCode = 1;
  } else {
    process.stdout.write('Generated overloads are up to date.\n');
  }
}

await main();
