// Generated by `libs/table/tools/generate-overloads.ts` — do not edit.
// Run `npm run table:overloads` to regenerate;
// `npm run table:overloads:check` fails if this file has drifted.

import type { Feature, Shape } from '../../engine/types';

export interface ComposeFeaturesOverloads {
  <In extends Shape, O1 extends object>(f1: Feature<In, O1>): Feature<In, O1>;
  <In extends Shape, O1 extends object, O2 extends object>(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
  ): Feature<In, O1 & O2>;
  <In extends Shape, O1 extends object, O2 extends object, O3 extends object>(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
  ): Feature<In, O1 & O2 & O3>;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
  ): Feature<In, O1 & O2 & O3 & O4>;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
    f5: Feature<In & O1 & O2 & O3 & O4, O5>,
  ): Feature<In, O1 & O2 & O3 & O4 & O5>;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
    f5: Feature<In & O1 & O2 & O3 & O4, O5>,
    f6: Feature<In & O1 & O2 & O3 & O4 & O5, O6>,
  ): Feature<In, O1 & O2 & O3 & O4 & O5 & O6>;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
    f5: Feature<In & O1 & O2 & O3 & O4, O5>,
    f6: Feature<In & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<In & O1 & O2 & O3 & O4 & O5 & O6, O7>,
  ): Feature<In, O1 & O2 & O3 & O4 & O5 & O6 & O7>;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
    f5: Feature<In & O1 & O2 & O3 & O4, O5>,
    f6: Feature<In & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<In & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
  ): Feature<In, O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8>;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
    f5: Feature<In & O1 & O2 & O3 & O4, O5>,
    f6: Feature<In & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<In & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
  ): Feature<In, O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9>;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
    f5: Feature<In & O1 & O2 & O3 & O4, O5>,
    f6: Feature<In & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<In & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9, O10>,
  ): Feature<In, O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10>;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
    f5: Feature<In & O1 & O2 & O3 & O4, O5>,
    f6: Feature<In & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<In & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9, O10>,
    f11: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10, O11>,
  ): Feature<In, O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11>;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
    f5: Feature<In & O1 & O2 & O3 & O4, O5>,
    f6: Feature<In & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<In & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9, O10>,
    f11: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10, O11>,
    f12: Feature<
      In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11,
      O12
    >,
  ): Feature<In, O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11 & O12>;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
    O13 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
    f5: Feature<In & O1 & O2 & O3 & O4, O5>,
    f6: Feature<In & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<In & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9, O10>,
    f11: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10, O11>,
    f12: Feature<
      In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11,
      O12
    >,
    f13: Feature<
      In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11 & O12,
      O13
    >,
  ): Feature<
    In,
    O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11 & O12 & O13
  >;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
    O13 extends object,
    O14 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
    f5: Feature<In & O1 & O2 & O3 & O4, O5>,
    f6: Feature<In & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<In & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9, O10>,
    f11: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10, O11>,
    f12: Feature<
      In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11,
      O12
    >,
    f13: Feature<
      In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11 & O12,
      O13
    >,
    f14: Feature<
      In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11 & O12 & O13,
      O14
    >,
  ): Feature<
    In,
    O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11 & O12 & O13 & O14
  >;
  <
    In extends Shape,
    O1 extends object,
    O2 extends object,
    O3 extends object,
    O4 extends object,
    O5 extends object,
    O6 extends object,
    O7 extends object,
    O8 extends object,
    O9 extends object,
    O10 extends object,
    O11 extends object,
    O12 extends object,
    O13 extends object,
    O14 extends object,
    O15 extends object,
  >(
    f1: Feature<In, O1>,
    f2: Feature<In & O1, O2>,
    f3: Feature<In & O1 & O2, O3>,
    f4: Feature<In & O1 & O2 & O3, O4>,
    f5: Feature<In & O1 & O2 & O3 & O4, O5>,
    f6: Feature<In & O1 & O2 & O3 & O4 & O5, O6>,
    f7: Feature<In & O1 & O2 & O3 & O4 & O5 & O6, O7>,
    f8: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7, O8>,
    f9: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8, O9>,
    f10: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9, O10>,
    f11: Feature<In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10, O11>,
    f12: Feature<
      In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11,
      O12
    >,
    f13: Feature<
      In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11 & O12,
      O13
    >,
    f14: Feature<
      In & O1 & O2 & O3 & O4 & O5 & O6 & O7 & O8 & O9 & O10 & O11 & O12 & O13,
      O14
    >,
    f15: Feature<
      In &
        O1 &
        O2 &
        O3 &
        O4 &
        O5 &
        O6 &
        O7 &
        O8 &
        O9 &
        O10 &
        O11 &
        O12 &
        O13 &
        O14,
      O15
    >,
  ): Feature<
    In,
    O1 &
      O2 &
      O3 &
      O4 &
      O5 &
      O6 &
      O7 &
      O8 &
      O9 &
      O10 &
      O11 &
      O12 &
      O13 &
      O14 &
      O15
  >;
}
