name: CI

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          filter: tree:0
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'npm'

      - run: npm ci

      # TEMPORARY: excludes carried over from acme for known-failing test/build until fixed
      - run: npx nx run-many -t lint
      - run: npx nx run-many -t test --exclude=ng-table
      - run: npx nx run-many -t build --exclude=shared-table,ng-table
